### ISSUE TITLE
Private fields can't be accessed from members

### ISSUE THREAD

**Issue by remi-dupre** [joshua-maros/ouroboros#10]
Take the following code:

```
#[ouroboros::self_referencing]
struct SelfRef {
    buffer: String,
    #[borrows(buffer)]
    slice: &'this str,
    test: String,
}

impl SelfRef {
    fn display(&self) {
        println!("{}", &self.test)
    }
}
```

We get the following error:

```
error[E0616]: field `test` of struct `osm_reader::osm_store::ouroboros_impl_self_ref::SelfRef` is private
   --> src/osm_reader/osm_store.rs:264:30
    |
264 |         println!("{}", &self.test)
    |                              ^^^^ private field
```

The fields can correctly be accessed when they are public.

**Comment by joshua-maros** [comment]
This is intentional, you need to use `self.with_test()`. This mechanism ensures that the struct is not accessed or modified in a way that would cause undefined behavior or unsoundness. If you have a lot of extra fields in your struct which are not self-referential, you can make your code more readable by seperating your struct into a self-referencing part and a wrapper part. Your example would then become the following:
```rust
#[ouroboros::self_referencing]
struct SelfRef {
    buffer: String
    #[borrows(buffer}]
    slice: &'this str,
}

struct WrappedBuffer {
    self_ref_data: SelfRef,
    test: String,
}

impl WrappedBuffer {
    fn display(&self) {
        println!("{}", &self.test);
    }
}
```
I encourage this design pattern in general, as it also gives you control over how to expose the generated methods. For example, the following code does the same thing as `self.with_slice()` but is more ergonomic and easier to understand what purpose it serves:
```rust
impl WrappedBuffer {
    pub fn borrow_buffered_text(&self) -> &str {
        self.self_ref_data.with_slice(|s| *s)
    }
}
```
