### ISSUE TITLE
Compatibility with typed_arena

### ISSUE THREAD

**Issue by acriaer** [joshua-maros/ouroboros#12]
Hello,
there is a crate called _typed_arena_ that allows allocating objects who can hold circular references to each other:
https://docs.rs/typed-arena/2.0.1/typed_arena/

It would be useful if one could store such "arena" together with some references to its elements in the ouroboros' _self_referencing_ struct.
However, I find it currently impossible, since one has to have access to the struct's lifetime at the moment of arena declaration:
```
use std::cell::Cell;
use typed_arena::Arena;
use ouroboros::self_referencing;

struct Element<'a> {
    other: Cell<Option<&'a Element<'a>>>,
}

#[self_referencing]
struct MyStruct{
    arena: Box<Arena<Element<'this>>>, // one has to declare lifetime of the references stored in arena's objects
    #[borrows(arena)]
    root: &'this Element<'this>
}
```
which produces the following error:
```
error[E0261]: use of undeclared lifetime name `'this`
  --> src/main.rs:15:30
   |
13 | #[self_referencing]
   | - help: consider introducing lifetime `'this` here: `'this,`
14 | struct MyStruct{
15 |     arena: Box<Arena<Element<'this>>>,
   |                              ^^^^^ undeclared lifetime
```

Is there any fundamental reason why _'this_ is unavailable at line 15, or maybe such use-case could be introduced without much pain?

Many thanks.

**Comment by joshua-maros** [comment]
After some bug fixing and feature improvements, I've published version `0.6.0` which should work in your use case if you add `#[borrows()]` above the arena field.

Here's a summary of what's going on:
- The error is caused by the fact that Ouroboros thinks that the arena field isn't self-referencing, so it includes it in various parts of the generated code that allow you to separate it back out from the struct. Those parts of the code have no `'this` lifetime, causing the error.
- The feature I added was special handling for `borrows` annotation that have no arguments. Like other self-referencing fields, access to them is restricted to maintain safe behavior. Unlike other self-referencing fields, you do not need to use a builder function to construct them and can instead directly pass in the initial value.
- I also found a couple of bugs related to automatically generated `borrows_*` functions. In this case, they caused compiler errors, so I added detection for those cases to skip generating them.
