### ISSUE TITLE
Can't resolve lifetimes with `with_FIELD`

### ISSUE THREAD

**Issue by jsgf** [joshua-maros/ouroboros#15]
For example:

```
#[self_referencing]
struct Thing {
  head: String,
  #[borrows(head)]
  tail: &'this str
}

impl Thing {
  fn tail(&self) -> &str {
    self.with_tail(|tail: &&str| *tail)
  }
}
```
I think this should be fine because the returned `&str` lifetime should be the same as `&self`.

However, this fails to compile with
```
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
  --> src/main.rs:12:39
   |
12 |          self.with_tail(|tail: &&str| *tail)
   |                                       ^^^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the body at 12:25...
  --> src/main.rs:12:25
   |
12 |          self.with_tail(|tail: &&str| *tail)
   |                         ^^^^^^^^^^^^^^^^^^^
note: ...so that the expression is assignable
  --> src/main.rs:12:39
   |
12 |          self.with_tail(|tail: &&str| *tail)
   |                                       ^^^^^
   = note: expected `&str`
              found `&str`
note: but, the lifetime must be valid for the anonymous lifetime #1 defined on the method body at 11:5...
  --> src/main.rs:11:5
   |
11 |     fn tail(&self) -> &str {
   |     ^^^^^^^^^^^^^^^^^^^^^^
note: ...so that reference does not outlive borrowed content
  --> src/main.rs:12:10
   |
12 |          self.with_tail(|tail: &&str| *tail)
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

I think this is because the signature is:
```
        pub(super) fn with_tail<'outer_borrow, ReturnType>(
            &'outer_borrow self,
            user: impl for<'this> ::core::ops::FnOnce(&'outer_borrow &'this str) -> ReturnType,
        ) -> ReturnType {
            user(&self.tail)
        }
```
and the compiler can't work out that the lifetime in `ReturnType` should be the same as `'this`.

Would `with_tail_contents` have avoided this problem?

**Comment by joshua-maros** [comment]
Part of the kludginess that makes the crate work is the signature of the `with_` functions. Since Rust has no syntax to accurately describe a self-referencing lifetime, the `with_*` function instead requires that you pass a function that could work with *any* possible lifetime. This prevents you from storing self-references outside the struct or moving non-self-references into the struct. For some kinds of fields like plain references (including your `&'this str`), the macro knows it can generate an additional `borrow_*` function which correctly restricts the lifetime of the result to the lifetime of the initial borrow. You could use `borrow_tail()` in your example. If you have a field where that is not available, you can directly use `self.with_tail(|tail| *tail)` like so:

```rust
fn main() {
    let thing = Thing::new(
        String::from("Hello world!"),
        |head_ref| head_ref,
    );

    let head_ref = thing.with_tail(|tail_ref| *tail_ref);
    println!("{}", head_ref);
}
```
```
Hello world!
````
It is unfortunately not possible to wrap this usage of `with_*` in its own function, again being an unfortunate effect of the fact that Rust has no way to actually describe self-referencing lifetimes.
