### ISSUE TITLE
Discrepancy between build_FIELD and with_FIELD?

### ISSUE THREAD

**Issue by acriaer** [joshua-maros/ouroboros#16]
Hello,
I was further playing with arena-style allocations on version 0.7 and got stuck on the following issue:
```rust
use bumpalo::Bump;
use std::cell::Cell;
use ouroboros::self_referencing;

struct Element<'a> {
    other: Cell<Option<&'a Element<'a>>>,
}

#[self_referencing]
struct Graph {
    arena: Box<Bump>,
    #[borrows(arena)]
    pub root: &'this Element<'this>
}

fn make_graph() -> ouroboros_impl_graph::Graph {
    GraphBuilder {
        arena: Box::new(Bump::new()),
        root_builder: |arena: &Bump| {
            let e1 = arena.alloc(Element{other: Cell::new(None)});
            let e2 = arena.alloc(Element{other: Cell::new(Some(e1))});
            e1.other.set(Some(e2)); // make cycle
            e1 // works perfectly!
        },
    }.build()
}

fn main() {
    let mut graph = make_graph();
    //ok 

    graph.with_mut(|fields| {
        let new_root = &*fields.arena.alloc(Element{other: Cell::new(None)});
        *fields.root = new_root;
    });
    // error
}
```

This code which I deem reasonable (as I basically do the same thing in builder* and with*) gives the following problem:
```
error[E0597]: `graph` does not live long enough
  --> src/main.rs:32:5
   |
32 |       graph.with_mut(|fields| {
   |       -^^^^
   |       |
   |  _____borrowed value does not live long enough
   | |
33 | |         let new_root = fields.arena.alloc(Element{other: Cell::new(None)});
34 | |         *fields.root = new_root;
35 | |     });
   | |______- argument requires that `graph` is borrowed for `'static`
36 |       // error
37 |   }
   |   - `graph` dropped here while still borrowed

error: aborting due to previous error
```
I don't understand ouroboros' macros good enough to find out the exact cause, but if I move this code to a separate function like this:
```rust
fn change_root<'a>(graph: &'a mut Graph) -> &'a Element<'a>{
    let new_root: &'a Element<'a> = &*graph.borrow_arena().alloc(Element{other: Cell::new(None)});

    graph.with_root_mut(|root| {    
        *root = new_root;
        new_root
    })
}
```
The error is more revealing:
```
error[E0308]: mismatched types
  --> src/main.rs:32:21
   |
32 |         *root_ptr = new_root;
   |                     ^^^^^^^^ lifetime mismatch
   |
   = note: expected reference `&Element<'_>`
              found reference `&Element<'a>`
note: the anonymous lifetime #1 defined on the body at 31:25...
  --> src/main.rs:31:25
   |
31 |       graph.with_root_mut(|root_ptr| {    
   |  _________________________^
32 | |         *root_ptr = new_root;
33 | |         new_root
34 | |     })
   | |_____^
note: ...does not necessarily outlive the lifetime `'a` as defined on the function body at 28:16
  --> src/main.rs:28:16
   |
28 | fn change_root<'a>(graph: &'a mut Graph) -> &'a Element<'a>{
   |                ^^

error[E0308]: mismatched types
  --> src/main.rs:32:21
   |
32 |         *root_ptr = new_root;
   |                     ^^^^^^^^ lifetime mismatch
   |
   = note: expected reference `&Element<'_>`
              found reference `&Element<'a>`
note: the lifetime `'a` as defined on the function body at 28:16...
  --> src/main.rs:28:16
   |
28 | fn change_root<'a>(graph: &'a mut Graph) -> &'a Element<'a>{
   |                ^^
note: ...does not necessarily outlive the anonymous lifetime #1 defined on the body at 31:25
  --> src/main.rs:31:25
   |
31 |       graph.with_root_mut(|root_ptr| {    
   |  _________________________^
32 | |         *root_ptr = new_root;
33 | |         new_root
34 | |     })
   | |_____^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

So I think that the lifetime argument is not applied to the generic parameter of the Element when instantiating with_FIELD function, which causes it to fall to anonymous lifetime.

Many thanks

**Comment by joshua-maros** [comment]
It looks like this problem was caused when I converted the `with_*_contents` functions to just be `with_*`. I accidentally made this change to the `with_all` functions as well. I added back code so that the value of `fields.arena` is now of type `&'this Bump` rather than of type `&'outer_borrow Box<Bump>`. I've also added a test to ensure this functionality isn't broken in the future. The changes should be available soon under the version `0.8.0`.

**Comment by joshua-maros** [comment]
As a note, I've also modified some code in response to another issue that may require you to add `#[covariant]` to some of your fields. You will get a compiler error explaining why and how if that is the case.

**Comment by acriaer** [comment]
@joshua-maros OK, now with_mut works, but with_root_mut no longer works:
https://gist.github.com/acriaer/ab08f12f84197b0992a80db152c86e04

Also, as I understand root IS covariant, but if I use #[covariant], i get:
https://gist.github.com/acriaer/4f50b96c216eb76ef25996a234fe05e3

**Comment by joshua-maros** [comment]
The error when using `with_root_mut` is intentional. `new_root` has the type `&'a Element<'a>`, but `'a` is the lifetime that `graph` is borrowed for, meaning the element may no longer be valid as soon as that reference is dropped, but before the graph itself is dropped. It's therefore not valid for `'this`. Unfortunately, the only way to modify the code to work would be doing all the steps within a call to `with_mut`, a product of Rust's inability to accurately describe lifetimes which are self-referencing.

The second error is more puzzling. I thought the same thing, and tracked down the issue to being something with `Cell`:
```rust
struct Test {
    value: Cell<&'static i32>
}

impl Test {
    fn borrow<'a>(&'a self) -> &'a Cell<&'a i32> {
        &self.value
    }
}
```
The error is as follows:
```rust
error[E0308]: mismatched types
   --> src/main.rs:264:9
    |
264 |         &self.value
    |         ^^^^^^^^^^^ lifetime mismatch
    |
    = note: expected reference `&'a Cell<&'a i32>`
               found reference `&'a Cell<&'static i32>`
note: the lifetime `'a` as defined on the method body at 263:15...
   --> src/main.rs:263:15
    |
263 |     fn borrow<'a>(&'a self) -> &'a Cell<&'a i32> {
    |               ^^
    = note: ...does not necessarily outlive the static lifetime
```
The weird thing is that this works fine if you replace `Cell` with `Box` or `Option`, which I thought would have the same variance. I will do some more investigation.

**Comment by joshua-maros** [comment]
After revisiting the [Rustonomicon chapter on variance](https://doc.rust-lang.org/nomicon/subtyping.html#variance), the second error makes sense as well. Since `Cell` allows you to replace its contents, if the function were allowed to return a `Cell<&'a i32>`, you could give it a reference which only lasted as long as you borrowed the struct for, which could become invalid after that reference is dropped but the struct itself still exists. According to the chapter, this makes `Cell` invariant rather than covariant.
