### ISSUE TITLE
Patterns for reborrowing

### ISSUE THREAD

**Issue by kyku** [joshua-maros/ouroboros#54]
To make this question concrete: mysql crate has two structs, Connection and Transaction. Transaction borrows from Connection, and then, once it has been worked upon, needs to be committed. The commit operation consumes the Transaction (it takes it as self parameter). So when I'm done with one transaction, I'd like to start another one (this means calling start_transaction on the &mut Connection object), but I cannot access this.

One way of handling this I found is to shape my function to consume self, commit the transaction and return Heads which gives me the connection object back. Then I can construct a new instance of my wrapper object again from that. But this feels a bit of unergonomic.

Is there some better way?

**Comment by joshua-maros** [comment]
You are using `Heads` as intended. You want to take something out of a struct without borrowing it from that struct. Since you cannot take things directly out of the struct itself (for safety reasons), you must first get a `Heads` object which drops all things that are unsafe to access, then take the reference out from there. My only thought is that you can directly return the `&mut Connection` instead of returning the `Heads` struct.
