### ISSUE TITLE
Would a function that gets the value directly be sound?

### ISSUE THREAD

**Issue by Koxiaet** [joshua-maros/ouroboros#6]
In for example `BoxAndRef`, would the following methods not be sound?

```rust
pub fn get_data_contents(&self) -> &Box<i32>;
pub fn get_data_ref(&self) -> &&i32;
pub fn get_mut_data_ref(&mut self) -> &mut &i32;
```

As the lifetime of `self` is the same as the lifetime of the return type, `self` would be guaranteed not to move while those references exist. And a mutable reference to `data_ref` can't cause any harm as the user can only set `data_ref` to a lifetime longer than or equal to the lifetime of `self`, which would be sound.

Am I overlooking an obvious reason why this would be unsound?

**Comment by joshua-maros** [comment]
That was the way I originally wanted to design the crate. However, I discovered a soundness problem when experimenting with the design. The macro has to convert `'this` to `'ststic` since Rust has no way of representing the lifetime of the data itself. This means that the second function could be abused like this:
```rust
let data: &'static i32 = *self_ref_struct.get_data_ref();
drop(self_ref_struct);
// Compiles but causes a segmentation fault
println!("{:?}", *data);
```
However your comment has made me realize that the first function would be okay in some cases. Since **head** fields by definition do not borrow anything, it should be safe to allow directly retrieving a reference in the way you suggest. I think it would be good to add `borrow_#_contents` in addition to `with_#_contents` for any fields that are heads.

One note is that the return type would be `-> &i32` rather than `-> &Box<i32>`.

**Comment by Koxiaet** [comment]
@joshua-maros Why could it not be `&Box<i32>`? It's not possible to get a static reference from that if self lives as long as the implicit lifetime.

**Comment by joshua-maros** [comment]
It's mostly for consistency. Methods of the form `with_#_contents` are generated for fields which are borrowed immutably by other fields. Those other fields would receive a reference to the contents of the box rather than a reference to the box itself. I decided to make the `_contents` methods work the same way. I don't think giving a reference to the full box would cause any soundness problems, but since providing a reference to the contents would be more consistent anyway, I decided it would be safer to go down that route.

**Comment by joshua-maros** [comment]
I ended up revisiting this due to another issue (https://github.com/solana-labs/solana/pull/13555). The new version of the crate, `0.5.1`, generates `borrow_#` and `borrow_#_contents` when possible, they are equivalent to doing `my_struct.with_field(|field| field);`.

**Comment by joshua-maros** [comment]
One note to add is that I investigated adding `borrow_#_mut` functions but that lead to the following problem:
```rust
let self_referencing = make_instance();
let some_data = make_some_data();
*self_referencing.borrow_data_ref_mut() = &some_data;
drop(some_data);
// This compiles fine.
println!("{:?}", self_referencing.borrow_data_ref());
```
The problem is that the `_mut` variant would have to return a type of `&'a mut &'a Data`, so we are able to give it a reference which only lasts as long as we borrow `self_referencing` for, leading to the reference being illegal after we drop `some_data`. It looks like using the `with_#_mut` approach is the only way to preserve safety when mutating.
